[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "pyra"
version = "0.2.5.dev0"
description = "A Python implementation of the GCL region algebra and query language described by Clarke et al."
readme = "README.md"
requires-python = ">=3.11"
license = "BSD-2-Clause"
license-files = ["LICENSE"]
authors = [{name = "Adam Fourney"}]
dependencies = ["ply==3.11"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://github.com/afourney/pyra"

[tool.setuptools]
packages = ["pyra"]
